// node{
//   stage('SCM Checkout'){
//     git 'https://github.com/abhisheknegi941/javaprojects'
//   }
//   stage('Compile-Package'){
//     // Get maven home path
//     def mvnHome = tool name: 'maven-3', type: 'maven'
//     sh "${mvnHome}/bin/mvn package"
//   }
// }
pipeline{
    agent any
    tools{
        maven 'maven3'
    }
    stages{
        stage("Create Folder"){
            steps{
                sh "mkdir -p ${env.JOB_NAME}"
            }
        }
        stage("Maven Build"){
            steps{
                sh 'mvn clean package'
            }
        }
        stage("Deploy to Tomcat Dev"){
            steps{
                tomcatDeploy('tomcat-dev','ec2-user','172.31.40.104')
            }
        }
    }
}
